apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: bets-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bets
  minReplicas: 1
  maxReplicas: 20
  targetCPUUtilizationPercentage: 70
